### PR TITLE
Reindex sync

### PR DESCRIPTION
**Pull request by dougsyer**
This worked but its definitely not fast.  Why would we run this vs zencatalog --reindex?

### CODE REVIEW

**Comment by burbel** [comment]
Have an alternate proposed solution; this change missed the transaction.commit() calls as well as the output incrementation.

**Comment by dougsyer** [comment]
yea not surprised it was a quick hack to get it running in a semi-emergency.

**Comment by burbel** [comment]
Np thanks for the feedback and thanks for your patience.  I had an open
question on the syncdb() calls you mentioned in #38 - does the
_p_jar.sync() call remove the need for that?

**Comment by dougsyer** [comment]
yeah I manually edited the changes ing git and they didnt reflect the final changes I ended up using ...my bad.

**Pull request closed without merging**
